spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: "true"
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.MySQL5Dialect"
  database:
    driverClassName: "com.mysql.jdbc.Driver"
  datasource:
    url: "jdbc:mysql://mysqldb.c4v3j9tgecmv.us-east-1.rds.amazonaws.com:3306/itemsharing"
    username: "root"
    password: "{cipher}de8a2140acf533afcd9e1ee6f9156226581120ed6b49187e376694db634b7bad"
    testWhileIdle: "true"
    validationQuery: "SELECT 1"
    
    
server:
  port: 8081

eureka:
  instance:
    perferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://54.172.185.62:8761/eureka/

security:
 oauth2:
  resource:
    userInfoUri: http://54.172.185.62:8901/user
    
signing:
  key: 345345fsdgsf5345
  
logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.itemsharing: DEBUG